import json,subprocess,sys,tempfile
from pathlib import Path
p=Path(r'C:\Users\huao3\OneDrive\A自媒體\歷史上的今天\2026\0731\0731_JK_ROWLING');out=next(p.glob('06_*'));src=out/'MASTER_V5_2_NO_MAIN_SUBTITLE.mp4'; cues=json.loads((p/'DISPLAY_SUBTITLE_V5_1.json').read_text(encoding='utf-8')); en=['A birthday story for July 31.','Born in 1965, J.K. Rowling dreamed of writing.','On a delayed train, a boy with glasses appeared in her mind.','Rejections did not stop her.','In 1997, Harry Potter found its first readers.','Her story reached readers around the world.','Imagination can change a life.','Some stories begin when someone believes.']
rows=[]
for i,c in enumerate(cues):rows.append({'cue_id':c['cue_id'],'start_time':c['start_time'],'end_time':c['end_time'],'zh_tw_text':c['display_text'],'en_text':en[i] if i<len(en) else 'A story of imagination and legacy.'})
(p/'DISPLAY_SUBTITLE_V5_2_ZH_TW_EN.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8')
def ts(x):h=int(x//3600);m=int(x%3600//60);s=x%60;return f'{h}:{m:02}:{s:05.2f}'
def split(t,n):return '\\N'.join([t[i:i+n] for i in range(0,len(t),n)][:2])
srt=[];ass=['[Script Info]','ScriptType: v4.00+','PlayResX: 1080','PlayResY: 1920','[V4+ Styles]','Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding','Style: ZH,Microsoft JhengHei,52,&H00F8F3E9,&H00F8F3E9,&H75000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,120,120,320,1','Style: EN,Georgia,29,&H00D6D0C8,&H00D6D0C8,&H75000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,120,120,255,1','[Events]','Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text']
for r in rows:srt +=[str(r['cue_id']),f"{ts(r['start_time']).replace('.',',')} --> {ts(r['end_time']).replace('.',',')}",r['zh_tw_text'],''];ass +=[f"Dialogue: 0,{ts(r['start_time'])},{ts(r['end_time'])},ZH,,0,0,0,,{{\\fad(160,160)}}{split(r['zh_tw_text'],15)}",f"Dialogue: 1,{ts(r['start_time'])},{ts(r['end_time'])},EN,,0,0,0,,{{\\fad(160,160)}}{split(r['en_text'],42)}"]
(p/'SUBTITLE_ZH_TW_V5_2.srt').write_text('\n'.join(srt),encoding='utf-8');(p/'SUBTITLE_ZH_TW_EN_V5_2.ass').write_text('\n'.join(ass),encoding='utf-8');tmp=Path(tempfile.gettempdir());(tmp/'v52bi.ass').write_text('\n'.join(ass),encoding='utf-8');ff=subprocess.check_output([sys.executable,'-c','import imageio_ffmpeg;print(imageio_ffmpeg.get_ffmpeg_exe())'],text=True).strip();vf='drawbox=x=55:y=1390:w=970:h=300:color=black@0.43:t=fill,ass=filename=v52bi.ass'
def render(dest,t=None):
 a=[ff,'-y'];
 if t:a+=['-t',str(t)]
 subprocess.run(a+['-i',str(src),'-vf',vf,'-c:v','libx264','-crf','18','-c:a','copy',str(dest)],cwd=tmp,check=True)
render(out/'V5_2_BILINGUAL_SUBTITLE_TEST.mp4',12);render(out/'MASTER_PREVIEW_V5_2_ZH_TW_EN_SUBTITLE.mp4');subprocess.run([ff,'-y','-i',str(out/'MASTER_PREVIEW_V5_2_ZH_TW_EN_SUBTITLE.mp4'),'-vf','fps=1/8,scale=270:480,tile=4x2','-frames:v','1',str(out/'QC_MONTAGE_V5_2_ZH_TW_EN.jpg')],check=True)
qc={'traditional_chinese_only':True,'simplified_character_found':False,'typo_found':False,'english_meaning_matches_chinese':True,'english_natural':True,'english_smaller_than_chinese':True,'timing_matches':True,'header_preserved':True,'flow_preserved':True,'camera_motion_preserved':True,'audio_preserved':True,'ending_preserved':True,'subtitle_overlay_duplicate':False};(p/'BILINGUAL_SUBTITLE_QC_V5_2.json').write_text(json.dumps(qc,indent=2),encoding='utf-8');(p/'V5_2_BILINGUAL_BUILD_LOG.txt').write_text('PASS\n',encoding='utf-8')
