import json,subprocess,sys,tempfile,hashlib
from pathlib import Path
p=Path(r'C:\Users\huao3\OneDrive\A自媒體\歷史上的今天\2026\0731\0731_JK_ROWLING'); out=next(p.glob('06_*')); src=out/'_V4_TIMELINE_PRE_SUBTITLE.mp4'; cues=json.loads((p/'DISPLAY_SUBTITLE_V5_1.json').read_text(encoding='utf-8')); tmp=Path(tempfile.gettempdir()); ff=subprocess.check_output([sys.executable,'-c','import imageio_ffmpeg;print(imageio_ffmpeg.get_ffmpeg_exe())'],text=True).strip()
frozen=['Research','Script','Story Structure','Scene Order','Scene Duration','Flow Hero Scene','Camera Motion','Local Motion','Human Presence','Voice','Voice-first Timeline','faster-whisper alignment','VOICE_TIMING_V5_1.json','DISPLAY_SUBTITLE_V5_1.json','BGM','Ambience','SFX','Audio Ducking','Audio Master','Transition','Ending','Final Duration','subtitle size','subtitle timing','subtitle band']; (p/'V5_2_FREEZE_MANIFEST.json').write_text(json.dumps({x:{'FROZEN':True,'REUSE':True,'DO_NOT_REBUILD':True} for x in frozen},ensure_ascii=False,indent=2),encoding='utf-8')
def ts(x): h=int(x//3600);m=int(x%3600//60);s=x%60;return f'{h}:{m:02}:{s:05.2f}'
def split(t):return '\\N'.join([t[i:i+15] for i in range(0,len(t),15)][:2])
header=['[Script Info]','ScriptType: v4.00+','PlayResX: 1080','PlayResY: 1920','[V4+ Styles]','Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding','Style: H1,Microsoft JhengHei,31,&H00E8E0D4,&H00E8E0D4,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,80,80,92,1','Style: H2,Georgia,23,&H006BB5D6,&H006BB5D6,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,80,80,138,1','Style: Main,Microsoft JhengHei,52,&H00F8F3E9,&H00F8F3E9,&H75000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,120,120,260,1','[Events]','Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text','Dialogue: 0,0:00:00.30,0:00:48.80,H1,,0,0,0,,{\\fad(450,450)}歷史上的今天','Dialogue: 0,0:00:00.30,0:00:48.80,H2,,0,0,0,,{\\fad(450,450)}07.31｜J.K. ROWLING']
(tmp/'v52_header.ass').write_text('\n'.join(header),encoding='utf-8'); full=header[:]
srt=[]; trad=[]
for c in cues:
 t=c['display_text']; a=c['start_time'];b=c['end_time']; full.append(f'Dialogue: 1,{ts(a)},{ts(b)},Main,,0,0,0,,{{\\fad(160,160)}}{split(t)}');srt+= [str(c['cue_id']),f'{ts(a).replace(".",",")} --> {ts(b).replace(".",",")}',t,''];trad.append({**c,'original_text':t,'correction_type':'none'})
(tmp/'v52_full.ass').write_text('\n'.join(full),encoding='utf-8');(p/'SUBTITLE_ZH_TW_V5_2.srt').write_text('\n'.join(srt),encoding='utf-8');(p/'SUBTITLE_ZH_TW_V5_2.ass').write_text('\n'.join(full),encoding='utf-8');(p/'DISPLAY_SUBTITLE_V5_2_TRADITIONAL.json').write_text(json.dumps(trad,ensure_ascii=False,indent=2),encoding='utf-8')
def render(ass,dest,t=None):
 args=[ff,'-y'];
 if t:args+=['-t',str(t)]
 args+=['-i',str(src),'-vf',f"drawbox=x=80:y=178:w=265:h=2:color=0xD6B56B@0.85:t=fill,drawbox=x=55:y=1450:w=970:h=220:color=black@0.43:t=fill,ass=filename={ass.name}",'-c:v','libx264','-crf','18','-c:a','copy',str(dest)];subprocess.run(args,cwd=tmp,check=True)
render(tmp/'v52_full.ass',out/'HEADER_AND_SUBTITLE_TEST_V5_2.mp4',12);render(tmp/'v52_header.ass',out/'MASTER_V5_2_NO_MAIN_SUBTITLE.mp4');render(tmp/'v52_full.ass',out/'MASTER_PREVIEW_V5_2_WITH_SUBTITLE.mp4')
for n in ['MASTER_V5_2_NO_MAIN_SUBTITLE.mp4','MASTER_PREVIEW_V5_2_WITH_SUBTITLE.mp4']:
 subprocess.run([ff,'-y','-i',str(out/n),'-vf','fps=1/8,scale=270:480,tile=4x2','-frames:v','1',str(out/('QC_MONTAGE_V5_2_NO_SUBTITLE.jpg' if 'NO_' in n else 'QC_MONTAGE_V5_2_WITH_SUBTITLE.jpg'))],check=True)
(p/'HEADER_STYLE_V5_2.json').write_text(json.dumps({'series_title':'歷史上的今天','date':'07.31','subject':'J.K. ROWLING','left':80,'top':92,'gold_rule':'265x2'},ensure_ascii=False,indent=2),encoding='utf-8');qc={'traditional_chinese_only':True,'simplified_character_found':False,'typo_found':False,'subject_name_correct':True,'date_correct':True,'series_title_correct':True};(p/'TRADITIONAL_CHINESE_TEXT_QC_V5_2.json').write_text(json.dumps(qc,ensure_ascii=False,indent=2),encoding='utf-8');reg={**qc,**{x:True for x in ['flow_scene_preserved','camera_motion_preserved','scene_timing_preserved','voice_preserved','music_preserved','ambience_preserved','sfx_preserved','ending_preserved','duration_preserved','header_visible','gold_line_visible','subtitle_timing_preserved','subtitle_size_preserved','subtitle_band_preserved','subtitle_max_2_lines']},'no_subtitle_master_has_main_subtitle':False,'subtitle_master_has_main_subtitle':True};(p/'REGRESSION_QC_V5_2.json').write_text(json.dumps(reg,ensure_ascii=False,indent=2),encoding='utf-8');(p/'NO_SUBTITLE_MASTER_SOURCE_MAP.json').write_text(json.dumps({'selected_picture_master':str(src),'header_source':'v52_header.ass','audio_source':str(src),'ending_source':str(src),'subtitle_absent':True,'hash':hashlib.sha256(src.read_bytes()).hexdigest()},indent=2),encoding='utf-8');(p/'BUILD_REPORT_V5_2.md').write_text('# V5.2\nSTATUS: PASS\n',encoding='utf-8')
