"""P1 constants derived from locked contracts."""
from mata_p0.constants import DEPENDENCY_STATUSES, EVIDENCE_STATUSES, GATE_IDS, GATE_STATUSES, LIFECYCLE_STATUSES
GATE_ORDER = tuple(GATE_IDS)
QC_STATUSES = frozenset({"NOT_EVALUATED", "PENDING", "PASS", "FAIL", "BLOCKED"})
EPISODE_STATUSES = frozenset({"NOT_STARTED", "IN_PROGRESS", "REVISION_REQUIRED", "READY", "APPROVED", "CLOSED", "NOT_EVALUATED"})
SEGMENT_STATUSES = frozenset({"NOT_STARTED", "IN_PROGRESS", "REVISION_REQUIRED", "READY", "APPROVED", "NOT_EVALUATED"})
