"""Stable identifiers for Local Studio."""

ARTIFACT_TYPES = (
    "EPISODE_BRIEF", "AUDIENCE_INSIGHT", "HOOK_STRATEGY",
    "CREATIVE_CANDIDATE", "CREATIVE_LOCK_CANDIDATE", "STORY_TREATMENT",
    "SCRIPT", "VOICEOVER", "DIALOGUE", "TIMELINE", "CHARACTER_BIBLE",
    "SCENE_BIBLE", "PROP_CONTINUITY", "LIGHTING_PROGRESSION",
    "EXACT_ASSET_LIST", "VISUAL_BIBLE", "STORYBOARD",
    "KEYFRAME_DEFINITION", "KEYFRAME_ASSET_REGISTRATION",
    "FLOW_PRODUCTION_PACKAGE", "FLOW_OUTPUT_REGISTRATION", "AUDIO_MANIFEST",
    "SRT_MANIFEST", "EDITING_PACKAGE", "FINAL_QC", "EPISODE_SUMMARY",
)
GATES = (
    "creative_lock", "story_lock", "story_visual_lock", "keyframe_lock",
    "production_lock", "final_approved",
)
LIFECYCLE = ("DRAFT", "REVIEW", "APPROVED", "LOCKED", "SUPERSEDED", "ARCHIVED", "REJECTED")
APPROVAL = ("NOT_SUBMITTED", "PENDING_HUMAN_REVIEW", "APPROVED", "REJECTED")
LOCK = ("UNLOCKED", "LOCKED")
PRODUCTION = (
    "AWAITING_CREATIVE_INPUT", "CREATIVE_REVIEW", "STORY_REVIEW",
    "VISUAL_REVIEW", "KEYFRAME_REVIEW", "PRODUCTION", "POST_PRODUCTION",
    "COMPLETE",
)
ROOT_FOLDER_CODE = "MATA_AI_ORIGINAL_VIDEO_STUDIO_OS_V2"
MAX_JSON_BYTES = 2 * 1024 * 1024
MAX_UPLOAD_BYTES = 200 * 1024 * 1024
